### ISSUE TITLE
Agregar paso de rollback en caso de fallo en staging

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/web-services#181]

**Comment by edipizarro** [comment]
PR: https://github.com/alercebroker/web-services/pull/227
Workflow:
 1) Se hace build y se sube nuevo chart a repo de web-services
 2) Se crea package localmente y se hace deploy utilizando package local
 3) Se genera healthcheck (falta test end-to-end)
 4) Si healthcheck falla se corre realiza rollback. El rollback retrocede en 1 la versión de los charts en el repo de web-services y realiza deploy desde ahí.

**Comment by edipizarro** [comment]
PR: https://github.com/alercebroker/web-services/pull/229
- Refactor workflow using action as template
- Added possible fix for the error when deploying new versions and older versions are used instead.
