### ISSUE TITLE
[Lightcurve] Actualizar respuestas y params según esquema multistream

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/web-services#184]
Se debe consultar tanto a PSQL como a MongoDB para acceder a las detecciones y no detecciones de ZTF. 

La respuesta a cada BD tiene esquemas distintos, pero puede tener información duplicada.

La respuesta final de la consulta de curva de luz debe limpiar las duplicadas y responder con la curva completa en el esquema multistream.

**Comment by ASHuenchuleo** [comment]
Que podemos considerar como duplicado? Que tenga el mismo mjd para un objeto dado?
