### ISSUE TITLE
Actualizar chart repo como parte de un único workflow (a.k.a. no usar chart-releaser-action)

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/web-services#192]

**Comment by dirodriguezm** [comment]
Se puede solucionar usando chart-releaser pero siguiedo la estrategia planteada en https://github.com/alercebroker/pipeline/issues/161#issuecomment-1760105977

**Comment by edipizarro** [comment]
Se utilizó el package local en vez de sacar chart-releaser
